export const MAP_STYLES = {
  light: [
    { "elementType": "geometry", "stylers": [{ "color": "#f8fafc" }] },
    { "elementType": "labels.icon", "stylers": [{ "visibility": "off" }] },
    { "elementType": "labels.text.fill", "stylers": [{ "color": "#64748b" }] },
    { "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "administrative", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "landscape", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "poi", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "road", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "transit", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "water", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "administrative", "stylers": [{ "visibility": "off" }] },
    { "featureType": "poi", "stylers": [{ "visibility": "off" }] },
    { "featureType": "poi.medical", "stylers": [{ "visibility": "on" }] },
    { "featureType": "poi.medical", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "road", "elementType": "geometry", "stylers": [{ "color": "#ffffff" }] },
    { "featureType": "road.highway", "elementType": "geometry", "stylers": [{ "color": "#f1f5f9" }] },
    { "featureType": "transit", "stylers": [{ "visibility": "off" }] },
    { "featureType": "water", "elementType": "geometry", "stylers": [{ "color": "#e2e8f0" }] }
  ],
  dark: [
    { "elementType": "geometry", "stylers": [{ "color": "#0B0F1A" }] },
    { "elementType": "labels.icon", "stylers": [{ "visibility": "off" }] },
    { "elementType": "labels.text.fill", "stylers": [{ "color": "#94a3b8" }] },
    { "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "administrative", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "landscape", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "poi", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "road", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "transit", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "water", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "administrative", "stylers": [{ "visibility": "off" }] },
    { "featureType": "poi", "stylers": [{ "visibility": "off" }] },
    { "featureType": "poi.medical", "stylers": [{ "visibility": "on" }] },
    { "featureType": "poi.medical", "elementType": "geometry", "stylers": [{ "color": "#86100E" }] },
    { "featureType": "poi.medical", "elementType": "labels.text.fill", "stylers": [{ "color": "#ef4444" }] },
    { "featureType": "poi.medical", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "off" }] },
    { "featureType": "road", "elementType": "geometry", "stylers": [{ "color": "#1e293b" }] },
    { "featureType": "road.highway", "elementType": "geometry", "stylers": [{ "color": "#334155" }] },
    { "featureType": "transit", "stylers": [{ "visibility": "off" }] },
    { "featureType": "water", "elementType": "geometry", "stylers": [{ "color": "#020617" }] }
  ]
};