-- Create hospitals table and insert initial data

-- Create the table
create table "public"."hospitals" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "address" text not null,
    "phone" text,
    "rating" double precision default 0,
    "type" text default 'standard', -- premium, standard, etc.
    "image" text,
    "specialties" text[] default '{}',
    "service_types" text[] default '{}',
    "features" text[] default '{}',
    "emergency_level" text,
    "available_beds" integer default 0,
    "ambulances_count" integer default 0,
    "wait_time" text,
    "price_range" text,
    "latitude" double precision,
    "longitude" double precision,
    "verified" boolean default false,
    "status" text default 'available', -- available, busy, full
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    primary key ("id")
);

-- Enable RLS
alter table "public"."hospitals" enable row level security;

-- Create policy to allow read access for everyone
create policy "Allow public read access"
on "public"."hospitals"
for select
using (true);

-- Insert initial data (derived from data/hospitals.js)
insert into "public"."hospitals" 
("name", "address", "phone", "rating", "type", "image", "specialties", "service_types", "features", "emergency_level", "available_beds", "ambulances_count", "wait_time", "price_range", "latitude", "longitude", "verified", "status")
values
(
    'City General Hospital',
    '123 Medical Plaza, Downtown',
    '+1-555-0123',
    4.8,
    'premium',
    'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=400',
    ARRAY['Emergency', 'General Care', 'Trauma'],
    ARRAY['premium', 'standard'],
    ARRAY['24/7 Emergency', 'Helicopter Landing', 'ICU', 'Surgery'],
    'Level 1 Trauma Center',
    5,
    3,
    '10 mins',
    '$150',
    37.7749,
    -122.4194,
    true,
    'available'
),
(
    'St. Mary''s Medical Center',
    '456 Healthcare Ave, Medical District',
    '+1-555-0456',
    4.9,
    'premium',
    'https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?w=400',
    ARRAY['Emergency', 'Cardiology', 'ICU'],
    ARRAY['premium', 'standard'],
    ARRAY['Cardiac Care', 'Stroke Center', 'ICU', 'Emergency'],
    'Level 2 Trauma Center',
    3,
    2,
    '15 mins',
    '$180',
    37.7849,
    -122.4094,
    true,
    'available'
),
(
    'University Medical Center',
    '100 University Ave, Medical Campus',
    '+1-555-0100',
    4.9,
    'premium',
    'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=400',
    ARRAY['Emergency', 'Neurology', 'Oncology', 'Research'],
    ARRAY['premium', 'standard'],
    ARRAY['Teaching Hospital', 'Research Center', 'Specialized Care', '24/7 Surgery'],
    'Level 1 Trauma Center',
    8,
    5,
    '20 mins',
    '$200',
    37.7449,
    -122.4494,
    true,
    'available'
),
(
    'Pacific Heart Institute',
    '800 Heartbeat Way, Medical Row',
    '+1-555-0800',
    4.95,
    'premium',
    'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=400',
    ARRAY['Cardiology', 'Cardiac Surgery', 'Emergency', 'ICU'],
    ARRAY['premium'],
    ARRAY['Cath Lab', 'Heart Surgery', 'ECMO', 'Cardiac ICU', 'Transplant Unit'],
    'Level 1 Cardiac Center',
    6,
    4,
    '8 mins',
    '$220',
    37.7820,
    -122.4150,
    true,
    'available'
),
(
    'Children''s Memorial Hospital',
    '500 Rainbow Drive, Children''s Campus',
    '+1-555-0500',
    4.92,
    'premium',
    'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400',
    ARRAY['Pediatrics', 'Pediatric Emergency', 'NICU', 'Pediatric Surgery'],
    ARRAY['premium', 'standard'],
    ARRAY['Child Life Services', 'PICU', 'NICU', 'Pediatric Surgery', 'Family Rooms'],
    'Level 1 Pediatric Trauma',
    12,
    3,
    '12 mins',
    '$175',
    37.7680,
    -122.4250,
    true,
    'available'
),
(
    'Emergency Care Unit',
    '789 Quick Response Blvd',
    '+1-555-0789',
    4.7,
    'standard',
    'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=400',
    ARRAY['Emergency', 'Urgent Care'],
    ARRAY['standard'],
    ARRAY['Fast Track', 'Urgent Care', 'X-Ray', 'Lab'],
    'Emergency Department',
    7,
    4,
    '5 mins',
    '$120',
    37.7649,
    -122.4294,
    true,
    'available'
),
(
    'Metro Health Center',
    '321 Community Care St',
    '+1-555-0321',
    4.6,
    'standard',
    'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=400',
    ARRAY['Emergency', 'Pediatrics'],
    ARRAY['standard'],
    ARRAY['Pediatric Care', 'Family Medicine', 'Basic Emergency'],
    'Community Hospital',
    4,
    2,
    '12 mins',
    '$100',
    37.7549,
    -122.4394,
    false,
    'busy'
),
(
    'Rapid Response Clinic',
    '45 Quick Care Lane',
    '+1-555-0045',
    4.5,
    'standard',
    'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400',
    ARRAY['Urgent Care', 'Minor Emergency'],
    ARRAY['standard'],
    ARRAY['Walk-in', 'Minor Injuries', 'Fast Service', 'X-Ray'],
    'Urgent Care Center',
    2,
    1,
    '5 mins',
    '$80',
    37.7849,
    -122.4294,
    true,
    'available'
),
(
    'Sunset Community Hospital',
    '600 Sunset Blvd',
    '+1-555-0600',
    4.55,
    'standard',
    'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=400',
    ARRAY['General Care', 'Emergency', 'Geriatrics'],
    ARRAY['standard'],
    ARRAY['Senior Care', 'Rehabilitation', 'Physical Therapy', 'Emergency'],
    'Community Hospital',
    6,
    2,
    '15 mins',
    '$95',
    37.7580,
    -122.4180,
    true,
    'available'
),
(
    'Bay Area Medical Clinic',
    '150 Bay Street',
    '+1-555-0150',
    4.4,
    'standard',
    'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400',
    ARRAY['Urgent Care', 'Family Medicine', 'Minor Surgery'],
    ARRAY['standard'],
    ARRAY['Walk-in Welcome', 'Same-Day Appointments', 'Lab Services'],
    'Urgent Care',
    3,
    1,
    '8 mins',
    '$85',
    37.7800,
    -122.4100,
    true,
    'available'
);
